apps/company_app/urls.py
from django.urls import path
from . import views

app_name = 'company'

urlpatterns=[
    path('company/register/menu', views.registerMenu, name="registerMenu"),
    path('company/register', views.newCompany, name="register"),
    path('company/splash', views.companySplash, name="splash"),
    path('company/edit/menu/<int:company_id>', views.editCompanyMenu, name="editMenu"),
    path('company/edit/<int:company_id>', views.editCompany, name="edit"),
    path('company/profile/<int:companyID>', views.profile, name='profile')
]

apps/event_app/urls.py
from django.urls import path
from . import views

app_name = 'event'

urlpatterns=[
    path('event/register/menu', views.registerMenu, name='register_menu'),
    path('event/register', views.register, name='register'),
    path('event/edit/menu/<int:event_id>', views.editMenu, name='editMenu'),
    path('event/<int:eventID>/job/signup/menu', views.jobMenu, name='jobMenu'),
    path('event/<int:eventID>/job/signup', views.jobSignUp, name='jobSignUp'),
    path('event/edit/<int:event_id>', views.edit, name='edit'),
    path('event/splash', views.eventSplash, name="splash"),
    path('event/dashboard/<int:event_id>', views.eventDashboard, name="dashboard"),
    path('event/<int:eventID>/new/post', views.newPost, name="newPost"),
    path('event/post/<int:postID>/new/comment', views.newComment, name="newComment"),
    path('event/<int:eventID>/user/signup', views.jobSignUp, name='signup'),
    path('event/<int:eventID>/delete_job/<int:jobID>', views.deleteJob, name='delete_job')
]

apps/login_app/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns=[
    path('', views.landingPage),
    path('login/menu', views.loginMenu),
    path('login', views.login),
    path('register/menu', views.registerMenu, name='register'),
    path('register', views.register),
    path('dashboard', views.dashboard, name='dashboard'),
    path('dashboard/<int:adminID>/admin', views.adminDashboard, name='admin_dashboard'),
    path('profile/<int:userID>', views.profile, name='profile'),
    path('edit/menu', views.editMenu, name="editMenu"),
    path('edit', views.edit, name="edit"),
    path('logout', views.logout),
    path('getNavBar', views.getNavBar),
    path('generate', views.generate)
    # path('users/<int:userID>', views.user),
]

volunteer_project/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('apps.login_app.urls')),
    path('', include('apps.company_app.urls')),
    path('', include('apps.event_app.urls')),
]

apps/company_app/models.py
from django.db import models
import re
from datetime import date, datetime
from apps.login_app.models import User

#-----------------------Managers-------------------------#
class CompanyManager(models.Manager):
    errors={}
    def register_validator(self, postData):
        if len(postData['name'])<2:
            self.errors['name']="must have more than 2 characters in first name"
        #add more validators: name unique, desc>200, address valid usps, website regex valid
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if not EMAIL_REGEX.match(postData['email']):
            self.errors['email']='enter valid email'
        if len(postData['description'])<150:
            self.errors['description']='Description should be over 150 characters long'
        return self.errors
    def edit_validator(self, postData, my_id):
        if len(postData['name'])<2:
            self.errors['name']="edit: must have more than 2 characters in name"
        #add more to editing
        return self.errors
#-----------------------Models-------------------------#
class CompanyType(models.Model):
    def __repr__(self):
        return f"< Item from companyType table: {self.category}>"
    category = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    #foreign key 'companies'

class Company(models.Model):
    def __repr__(self):
        return f"< Item from company table: {self.name}>"
    name = models.CharField(max_length=45)
    description = models.CharField(max_length=150)
    category = models.ForeignKey(CompanyType, related_name='companies', on_delete=models.CASCADE, default=None, null=True)
    admins = models.ManyToManyField(User, related_name="company_admin")
    address = models.CharField(max_length=45)
    website = models.CharField(max_length=90, default='')
    # color-theme
    email = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = CompanyManager()
    #foreign key 'events_owned'
    #foreign key 'events_contributed'
    #foreign key 'events_sponsored'

apps/company_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Company, CompanyType
from ..event_app.models import Event, Job, JobType
from ..login_app.models import User
from datetime import datetime
import bcrypt

# render register company menu if logged in
def registerMenu(request):
    if 'user' in request.session:
        return render(request, 'register_company.html')
    else:
        return redirect('/')

# render company profile page, allowed for public view
def profile(request, companyID):
    context={
        'company':Company.objects.get(id=companyID)
    }
    return render(request, 'company_profile.html', context)

#  validation for admin and adjust the admin status once validated
def newAdmin(request, company_id):
    user=User.objects.filter(email=request.POST['admin'])
    if len(user) ==0:
        messages.error(request, 'this email has no associated user')
        return False
    else:
        admin=user[0]
        company=Company.objects.get(id=company_id)
        company.admins.add(admin)
        company.save()
    return True

# edit company, does not allow name field of Company to be edited
# security features need to be edited****
def editCompany(request, company_id):
    errors=Company.objects.edit_validator(request.POST, company_id)
    if validation(request, errors):
        if request.POST['admin'] != "":
            if not newAdmin(request, company_id):
                return redirect('company:editMenu', company_id=company_id)
        company=Company.objects.get(id=company_id)
        company.name=request.POST['name']
        company.email=request.POST['email']
        company.description=request.POST['description']
        company.address=request.POST['address']
        company.website=request.POST['website']
        company.save()
    return redirect('/')

# register a new company
def newCompany(request):
    errors=Company.objects.register_validator(request.POST)
    if validation(request, errors):
        #debugging adding category
        CompanyType.objects.create(category="test category")
        my_category=CompanyType.objects.last()
        #end debugging category
        admin=request.session['user']
        Company.objects.create(name=request.POST['name'], description=request.POST['description'], address=request.POST['address'], website=request.POST['website'], email=request.POST['email'], category=my_category)
        Company.objects.last().admins.add(User.objects.get(id=admin))
        return redirect(f'/dashboard/{admin}/admin')
    else:
        return redirect('/')

# splash page for company, renders thumbnail images of existing companies in database
def companySplash(request):
    context={
        'companies':Company.objects.all()
    }
    if 'user' in request.session:
        context['user']=User.objects.get(id=request.session['user'])
    return render(request, 'company_splash.html', context)

# edit company menu, must be admin of company to edit
def editCompanyMenu(request, company_id):
    if 'user' in request.session:
        context={
            'company': Company.objects.get(id=company_id)
        }
        return render(request, 'edit_company.html', context)
    else:
        return redirect('/')

# helper method: validator for logging error messages
def validation(request, errors):
    if(len(errors)>0):
        for key, val in errors.items():
            messages.error(request, val)
            return False
    return True

apps/company_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Template{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script>
        $(function(){
                $.get("/getNavBar",function(data){
                    $("#navBar").append(data);
                });    
        })
    </script>
    {% block head %}
    {% endblock head %}
</head>
<body>
    <div class="container">
        <div class="header">
            {% block navbar %} <div id='navBar'></div> {% endblock navbar %}
            {% block header %}{% endblock header %}
        </div>
        <div class="body">
            {% block body %}{% endblock body %}
        </div>
        <div class="footer">
            {% block footer %}{% endblock footer %}
        </div>
    </div>
</body>
</html>

apps/company_app/templates/company_profile.html
{% extends "base.html" %}
{% block title %}
&circlearrowright; V-Time | {{company.name}} | Profile
{% endblock title %}
{% block body %}
<div class="justify-content-center">
    <div class="card">
        <div class="card-header" style="background-color: #009ac7; color: #e5f3f9;">
            Company Profile
        </div>
        <div class="card-body">
        
            <div class="media">
                <img class="mr-3" src="https://picsum.photos/seed/{{company.name}}/300" alt="Generic placeholder image">
                <div class="media-body">
                    <h5 class="card-title">{{company.name}}</h5>
                    <p class="card-text">{%lorem%}</p>
                </div>
            </div>
        
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                {%for event in company.events_owned.all%}
                <h5 class="card-title"><a href="{%url 'event:dashboard' event_id=event.id%}">{{event.name}}</a></h5>
                <hr>
                {%endfor%}
            </li>
            <li class="list-group-item">Category: {{company.category.category}}</li>
            <li class="list-group-item">Admin: 
                {%for admin in company.admins.all%}
                <a href="{%url 'login:profile' userID=admin.id%}">{{admin.first_name}} {{admin.last_name}}</a>
                {%endfor%}
            </li>
            <li class="list-group-item">Email: {{company.email}}</li>
            <li class="list-group-item">Website: <a href={{company.website}}>{{company.website}}</a></li>
            <li class="list-group-item">Location: {{company.address}}</li>
            <li class="list-group-item">Registered: {{company.created_at}}</li>
        </ul>
    </div>
</div>
{% endblock %}

apps/company_app/templates/company_splash.html
{% extends "base.html" %}
{% block title %}
&circlearrowright; V-Time Platform | Companies
{% endblock title %}
{% block body %}
<div class="justify-content-center">
    <div class="card">
        <div class="card-header" style="background-color: #009ac7; color: #e5f3f9;">
            <input class="rounded-pill text-center p-1" style="font-size: smaller;" type="text" name="search" id="search" placeholder="Search Companies!">
            <span class="text-right float-right">
                <a href="" data-toggle="modal" data-target="#register-company" style="color: #e5f3f9;">Register Company</a>
            </span>
        </div>
        <div class="card-body bg-dark">
            <div class="card-columns">
                <div  id='companies'>
                {% for company in companies %}
                        <div class="card" >
                            <div class="card-body">
                                {%load static%}
                                <a href="{%url 'company:profile' companyID=company.id%}"><img class="card-img-top" src="https://picsum.photos/seed/{{company.name}}/300"  alt="Card image cap"></a>
                                <hr>
                                <h5 class="card-title" style="text-align: center;"><a href="{%url 'company:profile' companyID=company.id%}">{{company.name}}</a></h5>
                                <h6 class="card-subtitle mb-2 text-muted">Category: {{company.category.category}}</h6>
                                <div class="card-text">
                                    {% if user in company.admins.all %}
                                    <a href="{% url 'company:editMenu' company_id=company.id %}">Edit me</a>
                                    {% endif %}
                                    {% if user.level == 9 %}
                                    <a href="{% url 'company:editMenu' company_id=company.id %}">Admin Edit</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </div> 
    <!-- register company modal -->
    <div class="modal fade" id="register-company" role="dialog">
        <div class="modal-dialog modal-lg">
            <!-- <div class="card" style="width: 60rem; height: 40rem;">{{graph|safe}}</div> -->
            <div class="modal-content">
            <div class="modal-header"  style="background-color: #009ac7; color: #e5f3f9;">
                <!-- <button type="button" class="close" data-dismiss="modal">&times;</button> -->
                <h4 class="modal-title">Hi, {{user.first_name}}! Register your company!</h4>
            </div>
            <div class="modal-body">
                <form action="{% url 'company:register' %}" method="POST">
                    {%csrf_token%}
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>Whoops!</strong> {{message}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endfor %}
                    {% endif %}
                    <div class="form-group">
                        <label for="name">Company Name</label>
                        <input type="text" class="form-control" name="name" id="name">
                    </div>
                    <div class="form-group">
                        <label for="description">Description (>150char)</label>
                        <input type="text" class="form-control" name="description" id="description">
                    </div>
                    <div class="form-group">
                        <label for="email">Contact Email address</label>
                        <input type="email" class="form-control" name="email" id="email" value="@gmail.com">
                    </div>
                    <div class="form-group">
                        <label for="address">Address</label>
                        <input type="text" class="form-control" name="address" id="address" value="123 my street">
                    </div>
                    <div class="form-group">
                        <label for="website">Website</label>
                        <input type="text" class="form-control" name="website" id="website" value="testSite.com">
                    </div>
                    
                    <button type="submit" class="btn btn-success">Register</button>
                </form>
            </div>
            <div class="modal-footer"  style="background-color: #009ac7; color: #e5f3f9;">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="color: #e5f3f9;">Close</button>
            </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
    $("#search").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#companies div").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
    });
    });
</script>
{% endblock %}

apps/company_app/templates/edit_company.html
{% extends "base.html" %}
{% block title %}
Edit Company
{% endblock title %}
{% block body %}
<div class="d-flex justify-content-center">
    <div class="card-group">
        <div class="card" style="width: 26rem;">
            <div class="card-header">
                Edit Company
            </div>
            <div class="card-body">
                <form action="{% url 'company:edit' company_id=company.id %}" method="POST">
                    {%csrf_token%}
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>Whoops!</strong> {{message}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endfor %}
                    {% endif %}
                    <div class="form-group">
                        <label for="name">Company Name</label>
                        <input type="text" class="form-control" name="name" id="name" value="{{company.name}}">
                    </div>
                    <div class="form-group">
                        <label for="description">Description (>150char)</label>
                        <input type="text" class="form-control" name="description" id="description" value="{{company.description}}">
                    </div>
                    <div class="form-group">
                        <label for="email">Contact Email address</label>
                        <input type="email" class="form-control" name="email" id="email" value="{{company.email}}">
                    </div>
                    <div class="form-group">
                        <label for="address">Address</label>
                        <input type="text" class="form-control" name="address" id="address" value="{{company.address}}">
                    </div>
                    <div class="form-group">
                        <label for="website">Website</label>
                        <input type="text" class="form-control" name="website" id="website" value="{{company.website}}">
                    </div>
                    <div class="form-group">
                        <label for="admin">New admin's email</label>
                        <input type="email" class="form-control" name="admin" id="admin">
                    </div>
                    <button type="submit" class="btn btn-success">Save Changes</button>
                </form>
            </div>
        </div> 
    </div>
</div>
{% endblock %}

apps/company_app/templates/register_company.html
{% extends "base.html" %}
{% block title %}
Register Company
{% endblock title %}
{% block body %}
<div class="d-flex justify-content-center">
    <div class="card-group">
        <div class="card" style="width: 26rem;">
            <div class="card-header">
                New Compnay
            </div>
            <div class="card-body">
                <form action="{% url 'company:register' %}" method="POST">
                    {%csrf_token%}
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>Whoops!</strong> {{message}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endfor %}
                    {% endif %}
                    <div class="form-group">
                        <label for="name">Company Name</label>
                        <input type="text" class="form-control" name="name" id="name">
                    </div>
                    <div class="form-group">
                        <label for="description">Description (>150char)</label>
                        <input type="text" class="form-control" name="description" id="description">
                    </div>
                    <div class="form-group">
                        <label for="email">Contact Email address</label>
                        <input type="email" class="form-control" name="email" id="email" value="@gmail.com">
                    </div>
                    <div class="form-group">
                        <label for="address">Address</label>
                        <input type="text" class="form-control" name="address" id="address" value="123 my street">
                    </div>
                    <div class="form-group">
                        <label for="website">Website</label>
                        <input type="text" class="form-control" name="website" id="website" value="testSite.com">
                    </div>
                    
                    <button type="submit" class="btn btn-success">Register</button>
                </form>
            </div>
        </div> 
    </div>
</div>
{% endblock %}