apps/company_app/urls.py
from django.urls import path
from . import views

app_name = 'company'

urlpatterns=[
    path('company/register/menu', views.registerMenu, name="registerMenu"),
    path('company/register', views.newCompany, name="register"),
    path('company/splash', views.companySplash, name="splash"),
    path('company/edit/menu/<int:company_id>', views.editCompanyMenu, name="editMenu"),
    path('company/edit/<int:company_id>', views.editCompany, name="edit"),
    path('company/profile/<int:companyID>', views.profile, name='profile')
]

apps/event_app/urls.py
from django.urls import path
from . import views

app_name = 'event'

urlpatterns=[
    path('event/register/menu', views.registerMenu, name='register_menu'),
    path('event/register', views.register, name='register'),
    path('event/edit/menu/<int:event_id>', views.editMenu, name='editMenu'),
    path('event/<int:eventID>/job/signup/menu', views.jobMenu, name='jobMenu'),
    path('event/<int:eventID>/job/signup', views.jobSignUp, name='jobSignUp'),
    path('event/edit/<int:event_id>', views.edit, name='edit'),
    path('event/splash', views.eventSplash, name="splash"),
    path('event/dashboard/<int:event_id>', views.eventDashboard, name="dashboard"),
    path('event/<int:eventID>/new/post', views.newPost, name="newPost"),
    path('event/post/<int:postID>/new/comment', views.newComment, name="newComment"),
    path('event/<int:eventID>/user/signup', views.jobSignUp, name='signup'),
    path('event/<int:eventID>/delete_job/<int:jobID>', views.deleteJob, name='delete_job')
]

apps/login_app/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns=[
    path('', views.landingPage),
    path('login/menu', views.loginMenu),
    path('login', views.login),
    path('register/menu', views.registerMenu, name='register'),
    path('register', views.register),
    path('dashboard', views.dashboard, name='dashboard'),
    path('dashboard/<int:adminID>/admin', views.adminDashboard, name='admin_dashboard'),
    path('profile/<int:userID>', views.profile, name='profile'),
    path('edit/menu', views.editMenu, name="editMenu"),
    path('edit', views.edit, name="edit"),
    path('logout', views.logout),
    path('getNavBar', views.getNavBar),
    path('generate', views.generate)
    # path('users/<int:userID>', views.user),
]

volunteer_project/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('apps.login_app.urls')),
    path('', include('apps.company_app.urls')),
    path('', include('apps.event_app.urls')),
]

apps/event_app/models.py
from django.db import models
import re
from datetime import date, datetime
from apps.login_app.models import User
from apps.company_app.models import Company
#-----------------------Managers-------------------------#
class EventManager(models.Manager):
    errors={}
    def email_validator(self, postData):
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if not EMAIL_REGEX.match(postData['email']):
            return True
        return False 
    def register_validator(self, postData):
        if len(postData['name'])<2:
            self.errors['name']="must have more than 2 characters in event name"
        eTime=datetime.strptime[postData['time'], '%Y-%m-%d-%H-%M']
        if eTime <datetime.now():
            self.errors['time']="Event time must be in the future!!!"
        #add more validators: name unique, desc>200, address valid usps, website regex valid
        return self.errors
    def edit_validator(self, postData, event_id):
        if len(postData['name'])<2:
            self.errors['name']="edit: must have more than 2 characters in name"
        #add more to editing
        return self.errors
class JobManager(models.Manager):
    errors={}
    def create_validator(self, postData):
        return self.errors
    # def expired(self):
    #     if self.event.time < datetime.now():
    #         self.errors['expiredEvent']='this event has expired and cannot be signed up'
    #     return self.errors
class PostManager(models.Manager):
    errors={}
    def create_validator(self, postData):
        return self.errors
class CommentManager(models.Manager):
    errors={}
    def create_validator(self, postData):
        return self.errors

#-----------------------Models-------------------------#
class JobType(models.Model):
    def __repr__(self):
        return f"< Item from jobtype table: {self.name}>"
    name = models.CharField(max_length=45)
    description = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    #foreign key 'job_job_type'
    #foreign key 'requiredJobs_name'

class Event(models.Model):
    def __repr__(self):
        return f"< Item from event table: {self.name}>"
    # event methods============================================================

    # return sorted list with most recent to first
    def postsByTime(self):
        return self.posts.all().order_by('created_at').reverse()

    # event fields=============================================================
    name = models.CharField(max_length=45)
    description = models.CharField(max_length=150)
    owner = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="events_owned")
    contributors = models.ManyToManyField(Company, related_name="events_contributed")
    sponsors = models.ManyToManyField(Company, related_name="events_sponsored")
    time = models.DateTimeField(default=datetime.now)
    address = models.CharField(max_length=45, default='')
    website = models.CharField(max_length=90, default='')
    email = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = EventManager()
    #foreign key 'job_event'
    #foreign key 'posts'

class Job(models.Model):
    def __repr__(self):
        return f"< Item from job table: {self.name}>"
    jobType=models.ForeignKey(JobType, related_name='jobs', on_delete=models.CASCADE)
    # name=jobType.name
    # description=jobType.description
    user = models.ManyToManyField(User, related_name='jobs')
    hours = models.IntegerField(default=4) #change template default
    required_amount=models.IntegerField(default=10)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="job_event")
    review = models.CharField(max_length=150, default="")
    endorsement = models.CharField(max_length=150, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = JobManager()

class Post(models.Model):
    def __repr__(self):
        return f"< content from post table: {self.message}>"

    # return sorted comments with most recent to first
    def commentsByTime(self):
        return self.comments.all().order_by('created_at').reverse()

    user = models.ForeignKey(User, related_name="user_post", on_delete=models.CASCADE)
    event = models.ForeignKey(Event, related_name='posts', on_delete=models.CASCADE)
    message = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = PostManager()
    #foreign key 'comments'
    
class Comment(models.Model):
    def __repr__(self):
        return f"< content from comment table: {self.comment}>"
    user = models.ForeignKey(User, related_name="user_comment", on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    comment = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = CommentManager()

apps/event_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Event, Post, Job, Comment, JobType
from ..login_app.models import User
from ..company_app.models import Company


# redners event register menu if user is signed in
def registerMenu(request):
    if 'user' in request.session:
        user=User.objects.get(id=request.session['user'])
        context={
            'companies':user.company_admin.all(),
            'jobs':JobType.objects.all()
        }
        return render(request, 'register_event.html', context)
    else:
        return redirect('/')

# splash page for all existing events in db, does not require user to be signed in
# to view page
def eventSplash(request):
    context={
        'events':Event.objects.all()
    }
    if 'user' in request.session:
        context['user']=User.objects.get(id=request.session['user'])
        context['jobs']=JobType.objects.all()
    return render(request, 'event_splash.html', context)

# event profile page of a specific event identified by the id in the url
# does not require user to be sign in to view
def eventDashboard(request, event_id):
    if 'user' in request.session:
        context={
            'event': Event.objects.get(id=event_id),
            'user':User.objects.get(id=request.session['user'])
        }
    else:
        context={
            'event':Event.objects.get(id=event_id)
        }
    return render(request, 'event_dashboard.html', context)

# registration method for events
# fixes needed: job does not register
def register(request):
    errors=Event.objects.register_validator(request.POST) #need time validation in validator
    if validation(request, errors):
        # insert new position methods
        event=Event.objects.create(name=request.POST['name'], description=request.POST['description'], owner=Company.objects.get(id=request.POST['owner']), address=request.POST['address'], email=request.POST['email'], time=request.POST['time'])

        create_jobs(request, event.id)
        if 'website' in request.POST:
            event.website=request.POST['website']
        if 'contributors' in request.POST:
            event.contributors.add(Company.objects.get(id=request.POST['contributor']))
        if 'sponsors' in request.POST:
            event.sponsors.add(Company.objects.get(id=request.POST['sponsor']))
        return redirect('/event/splash')
    else:
        return redirect('/')

# edit method to edit upcoming event information
# fixes needed: need method for modifying associated jobs
def edit(request, event_id):
    errors=Event.objects.edit_validator(request.POST, event_id)
    if validation(request, errors):
        event=Event.objects.get(id=event_id)
        event.description=request.POST['description']
        event.time=request.POST['time']
        event.address=request.POST['address']
        event.email=request.POST['email']
        # need a way to delete jobs
        create_jobs(request, event_id)
        event.save()
        return redirect(f'/event/dashboard/{event_id}')
    else:
        return redirect(f'/event/edit/menu/{event_id}')

def create_jobs(request, event_id):
    print('starting create jobs')
    new_jobs = [[key, val] for key, val in request.POST.items() if 'amount' in key]
    for job in new_jobs:
        Job.objects.create(jobType=JobType.objects.get(id=job[0][7:]), event=Event.objects.get(id=event_id), hours=4, required_amount=job[1])

# renders edit menu for editing event
# mush be signed in to render
def editMenu(request, event_id):
    if 'user' in request.session:
        context={
            'event': Event.objects.get(id=event_id),
            'jobs':JobType.objects.all()
        }
        return render(request, 'edit_event.html', context)
    else:
        return redirect('/')

# menu to join an event
# only render when user is signed in
def jobMenu(request, eventID):
    if 'user' in request.session:
        context={
            'event':Event.objects.get(id=eventID)
        }
        return render(request, 'register_job.html', context)
    else:
        return redirect('/')

# method for user to signup for a job of event
def jobSignUp(request, eventID):
    if 'user' in request.session:
        # errors=Job.objects.expired()
        user=User.objects.get(id=request.session['user'])
        newJob=Job.objects.get(id=request.POST['jobID'])
        for job in user.jobs.all():
            if job.event.id==newJob.event.id:
                return redirect(f'/event/dashboard/{eventID}')
        if newJob.required_amount>len(newJob.user.all()):
            newJob.user.add(user)
        return redirect(f'/event/dashboard/{eventID}')
    else:
        return redirect('/')

def deleteJob(request, eventID, jobID):
    # TO DO- check if user is admin for event
    Job.objects.get(id=jobID).delete()
    return eventDashboard(request, eventID)
    
# method for creating new post to event
def newPost(request, eventID): 
    if 'user' in request.session:
        errors=Post.objects.create_validator(request.POST)
        if validation(request, errors):
            Post.objects.create(user=User.objects.get(id=request.session['user']), event=Event.objects.get(id=eventID),message=request.POST['message'])
        return redirect(f'/event/dashboard/{eventID}')
    else:
        return redirect('/')

# method for creating new comment to post
def newComment(request, postID):
    if 'user' in request.session:
        errors=Comment.objects.create_validator(request.POST)
        if validation(request, errors):
            post=Post.objects.get(id=postID)
            Comment.objects.create(user=User.objects.get(id=request.session['user']),post=post, comment=request.POST['comment'])
        return redirect(f'/event/dashboard/{post.event.id}')
    else:
        return redirect('/')

# helper method: validates and generate error messages
def validation(request, errors):
    if(len(errors)>0):
        for key, val in errors.items():
            messages.error(request, val)
            return False
    return True

apps/event_app/templates/edit_event.html
{% extends "base.html" %}
{% block title %}
Edit Event
{% endblock title %}
{% block head %}
<script>
    $(document).ready(function(){
        var added_jobs={};
        $('#select_required_job').change(function(){ //when user selects a different job
            console.log('-------------------activating change function---------------')
            var job_id = $(this).val();
            var job_text = $("#select_required_job option:selected").text();
            
            
            if (added_jobs[job_id]!==undefined){
                console.log("if check passed")
                console.log('job already added')
            } else{
                console.log("begin else statement")
                added_jobs[job_id]=job_text
                console.log("added id "+job_id+" to dictionary "+added_jobs+", value: "+added_jobs[job_id]) // adding to added_jobs array
                console.log("selected job text: "+job_text);
                $('#job_selection').append(
                    '<div class="input-group mb-3" id="close_'+job_id+'">'+
                        '<div class="input-group-prepend">'+
                            '<div class="input-group-text">'+
                                '<button type="button" class="close" super_id="close_'+job_id+'" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+
                            '</div>'+
                        '</div>'+
                        '<fieldset disabled><input type="text" class="form-control" name="jobType_'+job_id+'" placeholder="'+job_text+'" aria-label="job type" aria-describedby="job type"></fieldset>'+
                        '<div class="input-group-append">'+
                            '<input type="number" class="form-control" placeholder="0" name="amount_'+job_id+'" id="number" aria-describedby="">'+
                        '</div>'+
                    '</div>'
                );
                console.log("removing option: "+$(".option[value="+job_id+"]").val()+" from option selector")//removing option
                $(".option[value="+job_id+"]").remove()
            
            }
            
        })
        $(document).on('click', '.close', function(){
            console.log("||||||||||||||activating click function||||||||||||||||")
            var job_id = $(this).attr("super_id").slice(6);
            console.log("job id: "+job_id)
            var job = added_jobs[job_id];
            console.log(job)
            current_id=$(this).attr('super_id');
            console.log("removing: "+current_id);
            $("#"+current_id).remove();
            
            console.log("new spliced array: "+added_jobs); //removing from added_jobs array
            console.log("adding option:"+job+" to option selector"); // adding option
            $("#select_required_job").append(
                `<option class= "option" value="${job_id}">${job}</option>`
            )
            delete added_jobs[job_id];
        })
        
    })
</script>
{% endblock head %}
{% block body %}
<div class="d-flex justify-content-center">
    <div class="card-group">
        <div class="card" style="width: 35rem;">
            <div class="card-header">
                Edit Event {{event.name}}
                ____update the form action ______
            </div>
            <div class="card-body">
                <form action="{% url 'event:edit' event_id=event.id %}" method="POST">
                    {%csrf_token%}
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>Whoops!</strong> {{message}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endfor %}
                    {% endif %}
                    <div class="form-group">
                        <label for="name">Event Name</label>
                        <input type="text" class="form-control" name="name" id="name" value="{{event.name}}">
                    </div>
                    <div class="form-group">
                        <label for="email">Event Associated Email</label>
                        <input type="email" class="form-control" name="email" id="email" value="{{event.email}}">
                    </div>
                    <div class="form-group">
                        <label for="phone_number">Phone Number</label>
                        <input type="text" class="form-control" name="phone_number" id="phone_number" value='9491234567'>
                    </div>
                    <div class="form-group">
                        <label for="time">Event Scheduled Time</label>
                        <input type="date" class="form-control" name="time" value='2020-09-29' id="time">
                    </div>
                    <div class="form-group">
                        <label for="website">Event Website</label>
                        <input type="text" class="form-control" name="website" value='' id="website">
                    </div>
                    <div class="form-group">
                        <label for="address">Event Location</label>
                        <input type="text" class="form-control" name="address" value='' id="address">
                    </div>
                    <div class="form-group">
                        <label for="description">Event About</label>
                        <textarea type="date" class="form-control" name="description" value='' id="description"></textarea>
                    </div>
                    <div class="" id="job_selection">
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlSelect1">Required Jobs</label>
                        <select class="form-control" id="select_required_job">
                            <option class="option" value="none"  selected>Select a Job Type</option>
                            {% for job in jobs %}
                            <option class= "option" value={{job.id}}>{{job.name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    
                    <button type="submit" class="btn btn-success disabled">Save Edits</button>
                </form>
            </div>
        </div> 
    </div>
</div>
{% endblock %}

apps/event_app/templates/event_dashboard.html
{% extends "base.html" %}
{% block title %}
&circlearrowright; V-Time | {{event.name}} | Info
{% endblock title %}
{% block body %}
{%load static%}
<link rel="stylesheet" href="{%static 'style.css'%}">
<div class="justify-content-center">
    <div class="card">
        <div class="card-header text-capitalize" style="background-color: #009ac7; color: #e5f3f9;">
            {{event.name}}
            {%if request.session.user %}
            <a class="float-right" href="" data-toggle="modal" data-target="#job-selection-form" style="color: #e5f3f9;">Join</a>
            {%else%}
            <a class="float-right" href="{%url 'login:register'%}">Signup Now!</a>
            {%endif%}
        </div>
        <div class="card-body">
            <div class="media">
                <img class="mr-3" src="https://picsum.photos/seed/{{event.name}}/300" alt="Generic placeholder image">
                <div class="media-body">
                    <h5 class="card-title"><span style="font-size: small; font-style: italic;">Hosted By:</span> <a href="{%url 'company:profile' companyID=event.owner.id%}">{{event.owner.name}}</a></h5>
                    <p class="card-text">{{event.description}} {%lorem%}</p>
                </div>
            </div>
        
        
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Time: {{event.time}}</li>
            <li class="list-group-item">Location: {{event.address}}</li>
            <li class="list-group-item">Contact: {{event.email}}</li>
            <li class="list-group-item">Partnering Companies:
                {%if event.contributors.all%}
                    {%for company in event.contributors.all%}
                        <a href="{%url 'company:profile' companyID=company.id%}">{{company.name}}</a>
                    {%endfor%}
                {%else%}
                    None
                {%endif%}
            </li>
            <li class="list-group-item">Sponsor Companies:
                {%if event.sponsors.all%}
                    {%for company in event.sponsors.all%}
                    <a href="{%url 'company:profile' companyID=company.id%}">{{company.name}}</a>
                    {%endfor%}
                {%else%}
                    None
                {%endif%}
            </li>
            <li class="list-group-item">
                {%if event.job_event.all%}
                <div class="accordion" id="accordionExample">
                    <div class="card">
                        <div class="card-header text-center">
                            <a data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" href="">Please volunteer for {{event.name}}!</a>
                        </div>
                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                            <div class="card-body">
                            Description of the role and Availability are listed below. Explore the wide range of volunteer work available on V-time and contribute to your local community and events by 
                            volunteering at one of our events! We hope to bring the community closer with these events and help those in need in our local community. Get recognize for your ability and 
                            work with endorsements and more!
                            </div>
                        </div>
                    </div>
                    {%for job in event.job_event.all%}
                    <div class="card">
                        <div class="card-header">
                            {% for company in user.company_admin.all %} <!--reuse the logic from before instead of having it display twice-->
                            {% if company == event.owner %} <!--also, in a for loop so there is a chance the if statement could proc more than once-->
                                <form action="{% url 'event:delete_job' eventID=event.id jobID=job.id%}" method="POST">
                                    {%csrf_token%}
                                    <button type="submit" class="close float-left mr-2">&times;</button>
                                </form>
                            {% endif %}
                            {% endfor %}
                            <a data-toggle="collapse" data-target="#job_{{job.id}}" aria-expanded="false" aria-controls="job_{{job.id}}" href="">{{job.jobType.name}}</a>
                            
                            <span class="badge float-right {% if job.user.all|length < 1 %} btn-success {% elif job.user.all|length < job.required_amount %}btn-warning{% else %}btn-danger{% endif %}">{{job.user.all|length}}/{{job.required_amount}}</span>
                        </div>
                        <div id="job_{{job.id}}" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                            <div class="card-body">
                                {{job.jobType.description}} 
                                <br>{%lorem%}
                            </div>
                        </div>
                    </div>
                    {%endfor%}
                </div>
                {%else%}
                None yet
                {%endif%}
            </li>
            {%if request.session.user%}
            <li class="list-group-item">
                <p class="card-text">
                    <form action="{%url 'event:newPost' eventID=event.id%}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="message">Ask <a href="{%url 'company:profile' companyID=event.owner.id%}">{{event.owner.name}}</a> questions or share your thoughts on the event!!!</label>
                            <textarea class="form-control" id="message" name="message" rows="3"></textarea>
                            <button class="btn btn-primary" type="submit">Post</button>
                        </div>
                    </form>
                </p>
            </li>
            {%endif%}
            {%if event.postsByTime%}
            <li class="list-group-item">
                <h5 class="card-title">Posts:</h5>
                <!-- accordion posts -->
                <div class="accordion" id='posts'>
                    {%for post in event.postsByTime%}
                    <div class="card">
                        <div class="card-header">
                            <h5><a data-toggle="collapse" data-target="#post_{{post.id}}" aria-expanded="true" aria-controls="collapseOne" href="">{{post.message}}</a> <span style="font-size: small;">by <a href="{%url 'login:profile' userID=post.user.id%}">{{post.user.first_name}}</a></span></h5>
                        </div>
                        <div id="post_{{post.id}}" class="collapse card-body" aria-labelledby="headingOne" data-parent="#posts">
                            {%for comment in post.commentsByTime%}
                            <div class="card-text border-bottom">
                                <p><a href="{%url 'login:profile' userID=comment.user.id%}">{{comment.user.first_name}}</a>: {{comment.comment}}</p>
                                <span style="font-size: smaller; font-style: italic; float: right;">{{comment.created_at}}</span>
                                <br>
                            </div>
                            {%endfor%}
                            <div class="card-body">
                                <p class="card-text">
                                    <form action="{%url 'event:newComment' postID=post.id%}" method="POST">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label for="comment">Leave a comment!</label>
                                            <textarea class="form-control" id="comment" name="comment" rows="3"></textarea>
                                            <button class="btn btn-primary" type="submit">Comment</button>
                                        </div>
                                    </form>
                                </p>
                            </div>
                        </div>
                    </div>
                    {%endfor%}
                </div>
                <!-- end of accordion -->
            </li>
            {%endif%}
        </ul>
    </div>
    <!-- job selection modal -->
    <div class="modal fade" id="job-selection-form" role="dialog">
        <div class="modal-dialog modal-lg">
            <!-- <div class="card" style="width: 60rem; height: 40rem;">{{graph|safe}}</div> -->
            <div class="modal-content">
            <div class="modal-header" style="background-color: #009ac7; color: #e5f3f9;">
                <!-- <button type="button" class="close" data-dismiss="modal">&times;</button> -->
                <h4 class="modal-title text-center">Welcome, {{user.first_name}}! Please select a role! </h4>
            </div>
            <div class="modal-body">
                <form action="{%url 'event:jobSignUp' eventID=event.id%}" method="POST">
                    {%csrf_token%}
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>Whoops!</strong> {{message}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endfor %}
                    {% endif %}
                    <div class="form-group">
                        <label for="exampleFormControlSelect1">Available Roles</label>
                        <select class="form-control" name="jobID" id="select_required_job">
                            <option class="option" selected>Select a Job</option>
                            {% for job in event.job_event.all %}
                            {%if job.user.all|length < job.required_amount%}
                            <option class= "option" value={{job.id}}>{{job.jobType.name}} || Positions filled: {{job.user.all|length}} / {{job.required_amount}}</option>
                            {%endif%}
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success">Confirm</button>
                </form>
            </div>
            <div class="modal-footer" style="background-color: #009ac7; color: #e5f3f9;">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="color: #e5f3f9;">Close</button>
            </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}