apps/company_app/urls.py
from django.urls import path
from . import views

app_name = 'company'

urlpatterns=[
    path('company/register/menu', views.registerMenu, name="registerMenu"),
    path('company/register', views.newCompany, name="register"),
    path('company/splash', views.companySplash, name="splash"),
    path('company/edit/menu/<int:company_id>', views.editCompanyMenu, name="editMenu"),
    path('company/edit/<int:company_id>', views.editCompany, name="edit"),
    path('company/profile/<int:companyID>', views.profile, name='profile')
]

apps/event_app/urls.py
from django.urls import path
from . import views

app_name = 'event'

urlpatterns=[
    path('event/register/menu', views.registerMenu, name='register_menu'),
    path('event/register', views.register, name='register'),
    path('event/edit/menu/<int:event_id>', views.editMenu, name='editMenu'),
    path('event/<int:eventID>/job/signup/menu', views.jobMenu, name='jobMenu'),
    path('event/<int:eventID>/job/signup', views.jobSignUp, name='jobSignUp'),
    path('event/edit/<int:event_id>', views.edit, name='edit'),
    path('event/splash', views.eventSplash, name="splash"),
    path('event/dashboard/<int:event_id>', views.eventDashboard, name="dashboard"),
    path('event/<int:eventID>/new/post', views.newPost, name="newPost"),
    path('event/post/<int:postID>/new/comment', views.newComment, name="newComment"),
    path('event/<int:eventID>/user/signup', views.jobSignUp, name='signup'),
    path('event/<int:eventID>/delete_job/<int:jobID>', views.deleteJob, name='delete_job')
]

apps/login_app/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns=[
    path('', views.landingPage),
    path('login/menu', views.loginMenu),
    path('login', views.login),
    path('register/menu', views.registerMenu, name='register'),
    path('register', views.register),
    path('dashboard', views.dashboard, name='dashboard'),
    path('dashboard/<int:adminID>/admin', views.adminDashboard, name='admin_dashboard'),
    path('profile/<int:userID>', views.profile, name='profile'),
    path('edit/menu', views.editMenu, name="editMenu"),
    path('edit', views.edit, name="edit"),
    path('logout', views.logout),
    path('getNavBar', views.getNavBar),
    path('generate', views.generate)
    # path('users/<int:userID>', views.user),
]

volunteer_project/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('apps.login_app.urls')),
    path('', include('apps.company_app.urls')),
    path('', include('apps.event_app.urls')),
]

apps/login_app/models.py
from django.db import models
from django.views.generic.base import TemplateView
import re
from datetime import date, datetime
from django.contrib import messages
import bcrypt
import plotly.offline as opy
import plotly.graph_objs as go

#-----------------------Managers-------------------------#
class UserManager(models.Manager):
    errors={}
    def email_validator(self, postData):
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if not EMAIL_REGEX.match(postData['email']):
            return True
        return False 
    def register_validator(self, postData):
        self.errors = {}
        if len(postData['first_name'])<2:
            print('firstName: '+postData['first_name'])
            self.errors['first_name']="must have more than 2 characters in first name"
        if len(postData['last_name'])<2:
            self.errors['last_name']="must have more than 2 characters in last name"
        if self.email_validator(postData):
            self.errors['email']= "Invalid email address!"
        allUsers=User.objects.all()
        for user in allUsers:
            if postData['email']==user.email:
                self.errors['emailUnique']="Email is already in use"
        if len(postData['password_initial'])<2:
            self.errors['passwordlen']="password must be >2 char"
        if postData['password_initial']!=postData['password_verify']:
            self.errors['password']="passwords must match"
        allUsers=User.objects.all()
        for user in allUsers:
            if postData['email']==user.email:
                self.errors['emailUnique']="Email is already in use"
        today=datetime.now()
        birthday=datetime.strptime(postData['birthday'],'%Y-%m-%d')
        if (today-birthday).days<4745: #this many days in 13 years
            self.errors['birthdayValid']="Must be >13"
        return self.errors
    def login_validator(self, postData):
        self.errors = {}
        if self.email_validator(postData):
            self.errors['email']= "Invalid email address!"
        user = User.objects.filter(email=postData['email'])
        if user:
            if 'userlogged' in self.errors:
                del self.errors['userlogged'] #clear error dictionary after page refresh
            logged_user = user[0] 
            if bcrypt.checkpw(postData['password'].encode(), logged_user.pw.encode()):
                if 'userpass' in self.errors:
                    del self.errors['userpass'] #clear error dictionary after page refresh
            else:
                self.errors['userpass']= "Invalid username or password" 
        else: self.errors['userlogged']= "Invalid username or password"    
        return self.errors
    def edit_validator(self, postData, my_id):
        self.errors  = {}
        if len(postData['first_name'])<2:
            self.errors['first_name']="edit: must have more than 2 characters in first name"
        if len(postData['last_name'])<2:
            self.errors['last_name']="edit: must have more than 2 characters in last name"
        if self.email_validator(postData):
            self.errors['email']= "edit: Invalid email address!"
        # allUsers = User.objects.all()
        # for user in allUsers:
        #     if user.id != my_id:
        #         if postData['email']==user.email:
        #             self.errors['emailUnique']="Email is already in use"
        return self.errors
#-----------------------Models-------------------------#
class User(models.Model):
    # user methods===============================================================
    def __repr__(self):
        return f"< Item from User table: {self.first_name}>"

    # returns all upcoming events, filter with datetime.now
    def upcomingEvents(self, n=5):
        return self.jobs.all().filter(event__time__gt=datetime.now())[:n]

    def allFutureEvents(self):
        return self.jobs.all().filter(event__time__gt=datetime.now())

    # returns past 5 events that has expired/participated
    def pastEvents(self, n=5):
        return self.jobs.all().filter(event__time__lt=datetime.now())[:n]

    def allPastEvents(self):
        return self.jobs.all().filter(event__time__lt=datetime.now())

    def powerUser(self):
        pu=User.objects.first()
        for user in User.objects.all():
            max=pu.vTime()
            if user.vTime() > max:
                pu=user
        return pu

    # returns the total amount of volunteer time
    def vTime(self):
        return sum(job.hours for job in self.jobs.all().filter(event__time__lt=datetime.now()))

    def avgVTime(self):
        return round(self.vTime()/len(self.jobs.all()), 1)

    # returns the 3 most recent post created by the user
    def recentPosts(self, n=3):
        return self.user_post.all().order_by('created_at').reverse()[:n]

    # returns the 3 most recent comment created by the user
    def recentComments(self, n=3):
        return self.user_comment.all().order_by('created_at').reverse()[:n]

    # returns a basic acitivity level line graph (output:div)
    def visualStat(self):
        x=[]
        y=[]
        for job in self.jobs.all().filter(event__time__lt=datetime.now()):
            print(job)
            x.append(job.event.name)
            y.append(job.hours)
        trace1 = go.Scatter(x=x, y=y, marker={'color': 'blue', 'symbol': 105, 'size': 14},
                            mode="lines",  name='1st Trace')
        data=go.Data([trace1])
        layout=go.Layout(title=f"{self.first_name} {self.last_name}'s Volunteer Activity", xaxis={'title':''}, yaxis={'title':'Volunteer Hours'})
        figure=go.Figure(data=data,layout=layout)
        # resizes the chart for modal
        figure.update_layout(
            autosize=False,
            width=450,
            height=300,
            margin=dict(
                l=50,
                r=50,
                b=60,
                t=60,
                pad=2
            )
        )
        div = opy.plot(figure, auto_open=False, output_type='div')
        return div
    # user fields=============================================================
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.CharField(max_length=90)
    alias = models.CharField(max_length=45)
    pw = models.CharField(max_length=90)
    birthday = models.DateTimeField()
    level = models.IntegerField(default=0)
    phone_number = models.CharField(max_length=15) #check out Twilio
    description = models.CharField(max_length=150, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()
    #foreign key 'company_admin'
    #foreign key 'jobs'
    #foreign key 'user_post'
    #foreign key 'user_comment'

apps/login_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User
from ..event_app.models import Event, Job, JobType
from ..company_app.models import Company, CompanyType
import bcrypt
from .generator import generate_companies, generate_events, generate_names, generate_categories, generate_jobTypes, assign_jobs, make_default_users, make_posts, make_comments, add_website
import random
from datetime import datetime


def getNavBar(request):
    context={}
    if 'user' in request.session:
        context={
            'username':User.objects.get(id=request.session['user'])
        }
    return render(request, 'navBar.html', context)

# redners template for the landing page
# SHOULD NOT REQUIRE TO BE SIGNED IN!!!
def landingPage(request):
    #```````````````I put this in to make a new company`
    context={}
    if 'user' in request.session:
        context={
            'username':User.objects.get(id=request.session['user'])
        }
    #```````````````end new company`
    return render(request, 'landingPage.html', context)

# renders login menu for user login
# SHOULD NOT REQUIRE TO BE SIGNED IN!!!
def loginMenu(request):
    if 'user' in request.session:
        return redirect('/dashboard')
    else:
        return render(request, 'login.html')

# method for logging in user
# SHOULD NOT REQUIRE TO BE SIGNED IN!!!
def login(request):
    errors=User.objects.login_validator(request.POST)
    if validation(request, errors):
        return redirect('/login/menu')
    else:
        user = User.objects.filter(email=request.POST['email'])
        if user:
            logged_user = user[0] 
            request.session['user']=logged_user.id
        return redirect('/dashboard')

# render register new user menu template
# SHOULD NOT REQUIRE TO BE SIGNED IN!!!
def registerMenu(request):
    if 'user' in request.session:
        return redirect('/event/splash')
    else:
        return render(request, 'register_user.html')

# method for registering new user
# SHOULD NOT REQUIRE TO BE SIGNED IN!!!
def register(request):
    errors=User.objects.register_validator(request.POST)
    if validation(request, errors):
        return redirect('/register/menu')
    else:
        newUser=User.objects.create(first_name=request.POST['first_name'],last_name=request.POST['last_name'], alias=request.POST['alias'] ,email=request.POST['email'],pw=bcrypt.hashpw(request.POST['password_initial'].encode(), bcrypt.gensalt()).decode(), birthday=request.POST['birthday'], phone_number=request.POST['phone_number'])
        request.session['user']=newUser.id
        return redirect('/dashboard')

# renders dashboard for user if signed in
def dashboard(request):
    if 'user' in request.session:
        user=User.objects.get(id=request.session['user'])
        context={
            'user':user,
            'graph':user.visualStat(),
            'all_users':User.objects.all()
        }
        return render(request, 'dashboard.html', context)
    else:
        return redirect('/')

# renders admin's dashboard if authorized as admin for company
def adminDashboard(request, adminID):
    if adminID==request.session['user']:
        context={
            'user':User.objects.get(id=request.session['user'])
        }
        return render(request, 'admin_dashboard.html', context)
    else:
        logout(request)
        messages.error(request, 'You are not an admin!')
        return redirect('/login/menu')

# renders user profile page if signed in
def profile(request, userID):
    if 'user' in request.session:
        context={
            'user':User.objects.get(id=userID)
        }
        return render(request, 'user_profile.html', context)
    else:
        user=User.objects.get(id=userID).first_name
        messages.error(request, f"Please signin to view {user}'s profile!")
        return redirect('/login/menu')

# renders user profile edit menu
def editMenu(request):
    if 'user' in request.session:
        context={
            'user':User.objects.get(id=request.session['user'])
        }
        return render(request, 'edit_user.html', context)
    else:
        return redirect('/')


# method to edit user profile
def edit(request):
    if 'user' in request.session:
        user_id=request.session['user']
        user=User.objects.get(id=user_id)
    errors=User.objects.edit_validator(request.POST, user_id)
    if validation(request, errors):
        return redirect('login:editMenu')
    else:
        user.first_name=request.POST['first_name']
        user.last_name=request.POST['last_name']
        user.alias=request.POST['alias']
        user.email=request.POST['email']
        user.phone_number=request.POST['phone_number']
        user.description=request.POST['description']
        if request.POST.getlist('adminlevel'):
            print("hello")
            if request.POST.getlist('adminlevel')[0]=='1':
                user.level=9
        user.save()
        return redirect('/dashboard')

# method to log out the user, clears session
def logout(request):
    request.session.clear()
    return redirect('/')

# helper method: validates and logs error messages
def validation(request, errors):
    if(len(errors)>0):
        for key, val in errors.items():
            messages.error(request, (key,val))
            return True
    return False

# generates dummy data for website
def generate(request):
    users = generate_names()
    events = generate_events()
    companies = generate_companies()
    categories = generate_categories()
    job_types = generate_jobTypes()
    if len(User.objects.all())<10:
        for user in users:
            User.objects.create(first_name=user[0],last_name=user[1], alias="bot" ,email=f'{user[0]}{user[1]}@gmail.com',pw=bcrypt.hashpw(user[0].encode(), bcrypt.gensalt()).decode(), birthday=datetime.today(), phone_number='(949)123-4565')
    if len(CompanyType.objects.all())<10:
        for category in categories:
            CompanyType.objects.create(category=category)
    if len(Company.objects.all())<50:
        for company in companies:
            category = CompanyType.objects.get(id=random.randint(1,len(CompanyType.objects.all())))
            newCompany=Company.objects.create(name=company,description='lorem ipsum says....',category=category,address=f'123 st boardwalk ave. suit 1', email=f'company@gg.com', )
            newCompany.admins.add(User.objects.get(id=random.randint(1,len(User.objects.all()))))
    if len(JobType.objects.all())<10:
        for job in job_types:
            JobType.objects.create(name=job[0], description=job[1])
    if len(Event.objects.all())<50:
        for event in events:
            company=Company.objects.get(id=random.randint(1,len(Company.objects.all())))
            newEvent=Event.objects.create(name=event, description=f'This is an event for!!!{company.description}', owner=company, address=f'123 st {company.name}-boardwalk ave. suit 1', email=f'{company.name}@gg.com')
            for i in range(random.randint(2,5)):
                newEvent.sponsors.add(Company.objects.get(id=random.randint(1,len(Company.objects.all()))))
                newEvent.contributors.add(Company.objects.get(id=random.randint(1,len(Company.objects.all()))))

            for i in range (random.randint(2,10)):
                Job.objects.create(jobType=JobType.objects.get(id=random.randint(1,len(JobType.objects.all()))),required_amount=random.randint(1,10), event=Event.objects.last(), hours=random.randint(1,8))
    make_default_users()
    assign_jobs()
    make_posts()
    make_comments()
    add_website()
    return redirect('/')

apps/login_app/templates/admin_dashboard.html
{% extends "base.html" %}
{% block title %}
&circlearrowright; V-Time | {{user.first_name}} {{user.last_name}} | Admin
{% endblock title %}
{% block body %}
<div class="justify-content-center">
    <div class="card">
        <div class="card-header" style="background-color: #009ac7; color: #e5f3f9;">
            Hello, {{user.first_name}}!
            <span class="text-right float-right">
                <a href="{% url 'login:dashboard' %}" style="color: #e5f3f9;">Back</a>
            </span>
        </div>
        <div class="card-body bg-dark">
            {%load static%}
            <div class="card-columns">
                {%for company in user.company_admin.all%}
                <div class="card">
                    <img class="card-img-top" src="{%static 'companyLogo.jpg'%}" alt="Card image cap">
                    <div class="card-body">
                    <h5 class="card-title">{{company.name}}</h5>
                    <p class="card-text">About: {{company.description}}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Admin: 
                            {%for admin in company.admins.all%} 
                                <a href="{%url 'login:profile' userID=admin.id%}">{{admin.first_name}} {{admin.last_name}}</a>
                            {%endfor%}
                        </li>
                        <li class="list-group-item">Email: {{company.email}}</li>
                        <li class="list-group-item">Website: {{company.website}}</li>
                        {%if company.events_owned.all%}
                        <li class="list-group-item">
                            Owner of Events
                            <hr>
                            {%for event in company.events_owned.all%}
                            <a href="{% url 'event:editMenu' event_id=event.id %}">{{event.name}} | </a>
                            {%endfor%}
                        </li>
                        {%endif%}
                        {% if company.events_contributed.all%}
                        <li class="list-group-item">
                            Contributor of Events
                            <hr>
                            {%for event in company.events_contributed.all%}
                            <a href="">{{event.name}}</a>
                            {%endfor%}
                        </li>
                        {%endif%}
                        {% if company.events_sponsored.all%}
                        <li class="list-group-item">
                            Sponsor of Events
                            <hr>
                            {%for event in company.events_sponsored.all%}
                            <a href="">{{event.name}}</a>
                            {%endfor%}
                        </li>
                        {%endif%}
                    </ul>
                    <div class="card-footer">
                        <a href="{%url 'company:editMenu' company_id=company.id%}">Edit Company</a>
                        <a href="{%url 'event:register_menu'%}" style="float: right;">Create Event</a>
                    </div>
                </div>
                {%endfor%}
            </div>
        </div>
    </div> 
</div>
{% endblock %}

apps/login_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Template{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script>
        $(function(){
                $.get("/getNavBar",function(data){
                    $("#navBar").append(data);
                });    
        })
    </script>
    {% block head %}
    {% endblock head %}
</head>
<body>
    <div class="container">
        <div class="header">
            {% block navbar %} <div id='navBar'></div> {% endblock navbar %}
            {% block header %}
            {% endblock header %}
        </div>
        <div class="body">
            {% block body %}
            {% endblock body %}
        </div>
        <div class="footer">
            {% block footer %}
            <div class="card-footer text-center bg-dark">
                <span class="text-center" style="color: #009ac7;">Copyright &copy; 2020 A&D. All rights reserved.</span>
            </div>
            {% endblock footer %}
        </div>
    </div>
    
</body>
</html>

apps/login_app/templates/edit_user.html
{% extends "base.html" %}
{% block body %}
<div class="d-flex justify-content-center">
    <div class="card-group">
        <div class="card" style="width: 26rem;">
            <div class="card-header">
                Edit User
            </div>
            <div class="card-body">
                <form action= "{% url 'login:edit' %}" method="POST">
                    {%csrf_token%}
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>Whoops!</strong> {{message}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endfor %}
                    {% endif %}
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" class="form-control" name="email" id="email" value={{user.email}}>
                    </div>
                    <div class="form-group">
                        <label for="first_name">First Name</label>
                        <input type="text" class="form-control" name="first_name" id="first_name" value={{user.first_name}}>
                    </div>
                    <div class="form-group">
                        <label for="last_name">Last Name</label>
                        <input type="text" class="form-control" name="last_name" id="last_name" value={{user.last_name}}>
                    </div>
                    <div class="form-group">
                        <label for="alias">Alias</label>
                        <input type="text" class="form-control" name="alias" id="alias" value={{user.alias}}>
                    </div>
                    <div class="form-group">
                        <label for="birthday">Birthday</label>
                        <input type="date" class="form-control" name="birthday" value='2001-09-29' id="birthday" value={{user.birthday}}>
                    </div>
                    <div class="form-group">
                        <label for="phone_number">Phone Number</label>
                        <input type="text" class="form-control" name="phone_number" id="phone_number" value={{user.phone_number}}>
                    </div>
                    <div class="form-group">
                        <label for="description">About</label>
                        <textarea type="text" class="form-control" name="description" id="description">{{user.description}}</textarea>
                    </div>
                    <input class="form-control" type="text" placeholder="level: {{user.level}}" readonly>
                    <div class="form-group form-check">
                        <input type="checkbox" class="form-check-input" value="1" id="adminlevel" name="adminlevel">
                        <label class="form-check-label" for="adminlevel">Check for super admin powers</label>
                    </div>
                    <button type="submit" class="btn btn-success">Save Changes</button>
                </form>
            </div>
        </div> 
    </div>
</div>
{% endblock %}

apps/login_app/templates/landingPage.html
{% extends "base.html" %}
{% block title %}
&circlearrowright; V-Time
{% endblock title %}
{% block body %}
<div class="jumbotron" style="color: aliceblue; background-size: cover; background-image: url(https://static.ebayinc.com/static/assets/Uploads/Stories/Articles/Untitled-1.jpg);">
    <h1 class="display-4">V-time Project!</h1>
    <p class="lead">Track your volunteer hours with V-time!</p>
    <hr class="my-4">
    <p style="text-shadow:
    -1px -1px 0 #000,  
    1px -1px 0 #000,
    -1px 1px 0 #000,
     1px 1px 0 #000;">
     A volunteer platform where companies and communities can devote resources for the greater good!</p>
    <a class="btn btn-primary btn-lg" href="/register/menu" role="button">Learn more</a>
    <p>
      {% if username %}
        Hello,{{username.first_name}} register a company please| 
        <a href="{% url 'company:registerMenu' %}">Register</a>
      {% endif %} 
    </p> 
  </div>
  {% if graph %}
<div style="width:600;height:500">
{{ graph|safe }}
</div>
{% endif %}
{% endblock body %}

apps/login_app/templates/navbar.html
    <nav class="navbar navbar-expand-lg navbar-light bg-dark" style="color: #009ac7;">
        <a class="navbar-brand" href="/" style="color: #009ac7;">V-Time</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto" style="color: #009ac7;">
                {%if request.session.user%}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login:dashboard' %}" style="color: #009ac7;">Home <span class="sr-only">(current)</span></a>
                </li>
                {%endif%}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'company:splash' %}" style="color: #009ac7;">Companies <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'event:splash' %}" style="color: #009ac7;">Events <span class="sr-only">(current)</span></a>
                </li>
                <!-- {% if request.session.user %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login:editMenu' %}">Edit Account</a>
                </li>
                {% endif %}  -->
            </ul>
            
            <span>
                {% if username%}
                Hello, {{username.alias}} {{username.first_name}} | <a href='/logout' style="color: aliceblue;">Logout</a>
                {% else %}
                NOT LOGGED IN  | <a href='/login/menu' style="color: ;">Login</a>
                {% endif %} 
            </span> 
            
        </div>
    </nav>
    <script>
        $(function(){
            console.log(window.location.pathname)
            $('a[href*="'+window.location.pathname+'"]').addClass('active')
        })
    </script>

apps/login_app/templates/user_profile.html
        {% extends "base.html" %}
        {% block title %}
        &circlearrowright; V-Time | {{user.first_name}} {{user.last_name}} | Profile
        {% endblock title %}
        {% block body %}
        <div class="justify-content-center">
            <div class="card">
                <!-- <div class="card-header">
                    User# {{user.id}}
                </div> -->
                <div class="card-body">
                    <div class="media">
                        {%load static%}
                        <img class="mr-3" src="{%static 'profilePic.png'%}" alt="dummy profile pic placeholder">
                        <div class="media-body">
                            <h5 class="card-title">{{user.first_name}} {{user.last_name}}</h5>
                            <p class="card-text">Description: {{user.description}} {%lorem%}</p>
                            </div>
                        </div>
                    </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Email: {{user.email}}</li>
                    <li class="list-group-item">Participating Events:
                        {% if user.upcomingEvents %}
                        <ul>
                            {% for job in user.upcomingEvents %}
                                <li><a href="{%url 'event:dashboard' event_id=job.event.id%}">{{job.event.name}}</a></li>
                            {% endfor %}
                        </ul>
                        {% else %}
                            None yet
                        {% endif %}
                    </li>
                    <li class="list-group-item">Past Events:
                        {% if user.pastEvents %}
                        <ul style="list-style:square;">
                            {% for job in user.pastEvents %}
                                <li><a href="{%url 'event:dashboard' event_id=job.event.id%}">{{job.event.name}}</a></li>
                            {% endfor %}
                        </ul>
                        {% else %}
                            None yet
                        {% endif %}
                    </li>
                    {%if user.user_post.all%}
                    <li class="list-group-item">
                        Posts:
                        <ul style="list-style: none;">
                            {%for post in user.user_post.all%}
                            <li><a href="{%url 'event:dashboard' event_id=post.event.id%}">{{post.message}}</a></li>
                            {%endfor%}
                        </ul>
                    </li>
                    {%endif%}
                </ul>
            </div>
        </div>
        {% endblock %}